@HotelListing.API_HostAddress = https://localhost:7082
@json = application/json
@apiKey=dXNlcjFAbG9jYWxob3N0LmNvbTpQQHNzrbd29yZDE=

@id=14
GET {{HotelListing.API_HostAddress}}/api/countries
# Authorization: Basic YWRtaW4xQGxvY2FsaG9zdC5jb206UEBzc3dvcmQx
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzMzViMDZhMi1kZGQ3LTQ0ODUtYThkYy1lN2FkYzA2Mzc0MDAiLCJlbWFpbCI6InVzZXJAbG9jYWxob3N0LmNvbSIsImp0aSI6ImNlYjc3NzRhLWY0M2UtNDhlOC04NmE4LWRiNWMzMWRiNGUyNCIsIm5hbWUiOiJWbGFkeW15cm92LCBEZW55cyIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IlVzZXIiLCJleHAiOjE3NzE3MDQ5NjUsImlzcyI6IkhvdGVsTGlzdGluZ0FQSSIsImF1ZCI6IkhvdGVsTGlzdGluZ0FQSUNsaWVudCJ9.gN_iuyQ0hGXow3w0nL--cnZXkLjdN_5GSepSr9BUSMo
###


GET {{HotelListing.API_HostAddress}}/api/countries/{{id}}

###

POST {{HotelListing.API_HostAddress}}/api/countries
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4NDg0MWFlZC1lMjZhLTQ3YzAtYWNlZC0yMjMyOGU3YWZjOTEiLCJlbWFpbCI6ImFkbWluQGxvY2FsaG9zdC5jb20iLCJqdGkiOiI2NDVhMmU4Ni1jNGRmLTRkMjYtODNlOC1kN2JkNDg5NmIyNDAiLCJuYW1lIjoiVmxhZHlteXJvdiwgRGVueXMiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbmlzdHJhdG9yIiwiZXhwIjoxNzcxNzA1MDM5LCJpc3MiOiJIb3RlbExpc3RpbmdBUEkiLCJhdWQiOiJIb3RlbExpc3RpbmdBUElDbGllbnQifQ.lDjqajp1MS-_G8psCJkwdkSba4pj-cRNw_KFqEyeEeg
Content-Type: {{json}}

{
  "name": "Test1 Country6",
  "shortName": "TC"
}

###

DELETE {{HotelListing.API_HostAddress}}/api/countries/{{id}}

###


PUT {{HotelListing.API_HostAddress}}/api/countries/{{id}}
Content-Type: {{json}}
{
  "id": 4,
  "name": "Jamaica!!",
  "shortName": "JM"
}

###

 // Hotels

###

GET {{HotelListing.API_HostAddress}}/api/hotels

###



GET {{HotelListing.API_HostAddress}}/api/hotels/{{id}}

###

POST {{HotelListing.API_HostAddress}}/api/hotels
Content-Type: {{json}}

{
  "Name": "Test Hotel 2222",
  "Address": "123 Main St",
  "Rating": 4.5,
  "CountryId": 1
}

###

DELETE {{HotelListing.API_HostAddress}}/api/hotels/{{id}}


###

PUT {{HotelListing.API_HostAddress}}/api/hotels/{{id}}
Content-Type: {{json}}

{
  "Id": 14,
  "Name": "ûגûגפûג",
  "Address": "123 Main St",
  "Rating": 4.5,
  "CountryId": 100
}

###

// Auth


###
POST {{HotelListing.Api_HostAddress}}/api/defaultauth/login
Content-Type: {{json}}

{
  "email": "admin1@localhost.com",
  "password": "P@ssword1"
}

###

POST {{HotelListing.Api_HostAddress}}/api/auth/register
Content-Type: {{json}}

{
  "email": "admin1@localhost.com",
  "password": "P@ssword1",
  "firstName":"Denys",
  "lastName": "Vladymyrov",
  "role": "Administrator"
}

###

GET {{HotelListing.Api_HostAddress}}/api/apikey
X-Api-Key: {{apiKey}}

###

GET {{HotelListing.Api_HostAddress}}/api/basicauth
Authorization: Basic dXNlcjFAbG9jYWxob3N0LmNvbTpQQHNzd29yZDE=

###
POST {{HotelListing.API_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "admin@localhost.com",
  "password": "P@ssword1"
}

###

POST {{HotelListing.API_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "email": "admin@localhost.com",
  "password": "P@ssword1",
  "firstName":"Denys",
  "lastName": "Vladymyrov",
  "role": "Administrator"
}

###
