@HotelListing.API_HostAddress = https://localhost:7082
@json = application/json
@apiKey=dXNlcjFAbG9jYWxob3N0LmNvbTpQQHNzrbd29yZDE=

@id=14
GET {{HotelListing.API_HostAddress}}/api/countries
Authorization: Basic YWRtaW4xQGxvY2FsaG9zdC5jb206UEBzc3dvcmQx

###


GET {{HotelListing.API_HostAddress}}/api/countries/{{id}}

###

POST {{HotelListing.API_HostAddress}}/api/countries
Content-Type: {{json}}

{
  "name": "Test Country6",
  "shortName": "TC"
}

###

DELETE {{HotelListing.API_HostAddress}}/api/countries/{{id}}

###


PUT {{HotelListing.API_HostAddress}}/api/countries/{{id}}
Content-Type: {{json}}
{
  "id": 4,
  "name": "Jamaica!!",
  "shortName": "JM"
}

###

 // Hotels

###

GET {{HotelListing.API_HostAddress}}/api/hotels

###



GET {{HotelListing.API_HostAddress}}/api/hotels/{{id}}

###

POST {{HotelListing.API_HostAddress}}/api/hotels
Content-Type: {{json}}

{
  "Name": "Test Hotel 2222",
  "Address": "123 Main St",
  "Rating": 4.5,
  "CountryId": 1
}

###

DELETE {{HotelListing.API_HostAddress}}/api/hotels/{{id}}


###

PUT {{HotelListing.API_HostAddress}}/api/hotels/{{id}}
Content-Type: {{json}}

{
  "Id": 14,
  "Name": "ûגûגפûג",
  "Address": "123 Main St",
  "Rating": 4.5,
  "CountryId": 100
}

###

// Auth


###
POST {{HotelListing.Api_HostAddress}}/api/defaultauth/login
Content-Type: {{json}}

{
  "email": "admin1@localhost.com",
  "password": "P@ssword1"
}

###

POST {{HotelListing.Api_HostAddress}}/api/auth/register
Content-Type: {{json}}

{
  "email": "admin1@localhost.com",
  "password": "P@ssword1",
  "firstName":"Denys",
  "lastName": "Vladymyrov",
  "role": "Administrator"
}

###

GET {{HotelListing.Api_HostAddress}}/api/apikey
X-Api-Key: {{apiKey}}

###

GET {{HotelListing.Api_HostAddress}}/api/basicauth
Authorization: Basic dXNlcjFAbG9jYWxob3N0LmNvbTpQQHNzd29yZDE=

###
POST {{HotelListing.API_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "amin4@localhost.com",
  "password": "P@ssword1"
}

###

POST {{HotelListing.API_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "email": "amin4@localhost.com",
  "password": "P@ssword1",
  "firstName":"Denys",
  "lastName": "Vladymyrov",
  "role": "Administrator"
}

###
